from ultralytics import YOLO

class train:
    def train_on_dataset(self): #this is done on google colab notebooks for GPU usage
        # Load a model
        model = YOLO('yolov8n-seg.pt')  # load a pretrained model (recommended for training)
        # Train the model
        results = model.train(data='data.yaml', epochs=100, imgsz=640)
        print(results)
        
    def train_on_weights(self): #this inputs the pretrained weights (by google colab) generated by the previous training code into a model
        model = YOLO('Training_files\\Training results\\100 Epochs + 50 Epochs (good fit)\\Second 50\\weights\\best.pt')
        return model
    
    def get_model(self):
        model = self.train_on_weights()
        return model

    
    